// Autogenerated from Pigeon (v3.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "MesiboPlugin.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}



@interface MesiboPluginMesiboPluginApiCodecReader : FlutterStandardReader
@end
@implementation MesiboPluginMesiboPluginApiCodecReader
@end

@interface MesiboPluginMesiboPluginApiCodecWriter : FlutterStandardWriter
@end
@implementation MesiboPluginMesiboPluginApiCodecWriter
@end

@interface MesiboPluginMesiboPluginApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation MesiboPluginMesiboPluginApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[MesiboPluginMesiboPluginApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[MesiboPluginMesiboPluginApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *MesiboPluginMesiboPluginApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    MesiboPluginMesiboPluginApiCodecReaderWriter *readerWriter = [[MesiboPluginMesiboPluginApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void MesiboPluginMesiboPluginApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MesiboPluginMesiboPluginApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.MesiboPluginApi.setup"
        binaryMessenger:binaryMessenger
        codec:MesiboPluginMesiboPluginApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setupToken:error:)], @"MesiboPluginMesiboPluginApi api (%@) doesn't respond to @selector(setupToken:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_token = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setupToken:arg_token error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.MesiboPluginApi.setPushToken"
        binaryMessenger:binaryMessenger
        codec:MesiboPluginMesiboPluginApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setPushTokenToken:voip:error:)], @"MesiboPluginMesiboPluginApi api (%@) doesn't respond to @selector(setPushTokenToken:voip:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_token = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_voip = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api setPushTokenToken:arg_token voip:arg_voip error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.MesiboPluginApi.sendMessage"
        binaryMessenger:binaryMessenger
        codec:MesiboPluginMesiboPluginApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(sendMessagePeer:message:error:)], @"MesiboPluginMesiboPluginApi api (%@) doesn't respond to @selector(sendMessagePeer:message:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_peer = GetNullableObjectAtIndex(args, 0);
        NSString *arg_message = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api sendMessagePeer:arg_peer message:arg_message error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.MesiboPluginApi.showUserList"
        binaryMessenger:binaryMessenger
        codec:MesiboPluginMesiboPluginApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(showUserListWithError:)], @"MesiboPluginMesiboPluginApi api (%@) doesn't respond to @selector(showUserListWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api showUserListWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.MesiboPluginApi.showMessages"
        binaryMessenger:binaryMessenger
        codec:MesiboPluginMesiboPluginApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(showMessagesPeer:error:)], @"MesiboPluginMesiboPluginApi api (%@) doesn't respond to @selector(showMessagesPeer:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_peer = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api showMessagesPeer:arg_peer error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.MesiboPluginApi.audioCall"
        binaryMessenger:binaryMessenger
        codec:MesiboPluginMesiboPluginApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(audioCallPeer:error:)], @"MesiboPluginMesiboPluginApi api (%@) doesn't respond to @selector(audioCallPeer:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_peer = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api audioCallPeer:arg_peer error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.MesiboPluginApi.videoCall"
        binaryMessenger:binaryMessenger
        codec:MesiboPluginMesiboPluginApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(videoCallPeer:error:)], @"MesiboPluginMesiboPluginApi api (%@) doesn't respond to @selector(videoCallPeer:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_peer = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api videoCallPeer:arg_peer error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
